# Generated by Django 3.1.2 on 2020-10-15 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SquirrelApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='squirrel',
            name='Age',
            field=models.CharField(default=0, help_text='Age', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Approaches',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Chasing',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Climbing',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Eating',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Foraging',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Indifferent',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Kuks',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Latitude',
            field=models.CharField(default='', help_text='Latitude discovered', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Location',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Longitude',
            field=models.CharField(default='', help_text='Longitude discovered', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Moans',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squirrel',
            name='OtherActivities',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='PrimaryFurColor',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Quaas',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Running',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squirrel',
            name='RunsFrom',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squirrel',
            name='Shift',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', help_text='shift', max_length=20),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='SpecificLocation',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='squirrel',
            name='TailFlags',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='squirrel',
            name='TailTwitches',
            field=models.BooleanField(blank=True, default=False),
            preserve_default=False,
        ),
    ]
