# Generated by Django 3.1.2 on 2020-10-15 03:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SquirrelApp', '0002_auto_20201015_0258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Age',
            field=models.CharField(default=0, help_text='Age', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Latitude',
            field=models.CharField(default='', help_text='Latitude discovered', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='LinktoUnique',
            field=models.URLField(default='', max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Longitude',
            field=models.CharField(default='', help_text='Longitude discovered', max_length=20),
        ),
    ]
