# Generated by Django 3.1.2 on 2020-10-15 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SquirrelApp', '0003_auto_20201015_0309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='squirrel',
            name='Latitude',
            field=models.CharField(blank=True, help_text='Latitude discovered', max_length=20),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='LinktoUnique',
            field=models.URLField(blank=True, max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='Longitude',
            field=models.CharField(blank=True, help_text='Longitude discovered', max_length=20),
        ),
    ]
