# Generated by Django 3.1.2 on 2020-10-16 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SquirrelApp', '0004_auto_20201015_0312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='squirrel',
            name='LinktoUnique',
        ),
        migrations.RemoveField(
            model_name='squirrel',
            name='id',
        ),
        migrations.AlterField(
            model_name='squirrel',
            name='UniqueSquirrelID',
            field=models.CharField(help_text='Unique Squirrel ID', max_length=100, primary_key=True, serialize=False),
        ),
    ]
