# Generated by Django 3.1.2 on 2020-10-16 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SquirrelApp', '0005_auto_20201016_0427'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sighting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('UniqueSquirrelID', models.CharField(help_text='Unique Squirrel ID', max_length=100)),
                ('Date', models.DateField(help_text='Date')),
                ('Latitude', models.CharField(blank=True, help_text='Latitude discovered', max_length=20)),
                ('Longitude', models.CharField(blank=True, help_text='Longitude discovered', max_length=20)),
                ('Shift', models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', help_text='shift', max_length=20)),
                ('Age', models.CharField(default=0, help_text='Age', max_length=20)),
                ('PrimaryFurColor', models.CharField(blank=True, max_length=20)),
                ('Location', models.TextField(blank=True)),
                ('SpecificLocation', models.CharField(blank=True, max_length=100)),
                ('Running', models.BooleanField(blank=True)),
                ('Chasing', models.BooleanField(blank=True)),
                ('Climbing', models.BooleanField(blank=True)),
                ('Eating', models.BooleanField(blank=True)),
                ('Foraging', models.BooleanField(blank=True)),
                ('OtherActivities', models.CharField(blank=True, max_length=100)),
                ('Kuks', models.BooleanField(blank=True)),
                ('Quaas', models.BooleanField(blank=True)),
                ('Moans', models.BooleanField(blank=True)),
                ('TailFlags', models.BooleanField(blank=True)),
                ('TailTwitches', models.BooleanField(blank=True)),
                ('Approaches', models.BooleanField(blank=True)),
                ('Indifferent', models.BooleanField(blank=True)),
                ('RunsFrom', models.BooleanField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Squirrel',
        ),
    ]
