# Generated by Django 3.1.2 on 2020-10-17 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SquirrelApp', '0007_squirrel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='Age',
            field=models.CharField(default=0, help_text='Age', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Approaches',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Chasing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Climbing',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Eating',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Foraging',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Indifferent',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Kuks',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Location',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Moans',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='OtherActivities',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='PrimaryFurColor',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Quaas',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Running',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='RunsFrom',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Shift',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', help_text='shift', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='SpecificLocation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='TailFlags',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='TailTwitches',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
