# Generated by Django 3.1.2 on 2020-10-19 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SquirrelApp', '0008_auto_20201017_2324'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='Latitude',
            field=models.FloatField(blank=True, help_text='Latitude discovered', max_length=20),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Longitude',
            field=models.FloatField(blank=True, help_text='Longitude discovered', max_length=20),
        ),
    ]
