# Generated by Django 3.1.2 on 2020-10-21 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SquirrelApp', '0009_auto_20201019_0208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='Latitude',
            field=models.FloatField(help_text='Latitude discovered', max_length=20),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Longitude',
            field=models.FloatField(help_text='Longitude discovered', max_length=20),
        ),
    ]
