# Generated by Django 3.1.2 on 2020-10-22 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SquirrelApp', '0010_auto_20201021_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='Approaches',
            field=models.BooleanField(blank=True, help_text='Approaches', null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Chasing',
            field=models.BooleanField(blank=True, help_text='Chasing', null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Climbing',
            field=models.BooleanField(blank=True, help_text='Climbing', null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Eating',
            field=models.BooleanField(blank=True, help_text='Eating', null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Foraging',
            field=models.BooleanField(blank=True, help_text='Foraging', null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Indifferent',
            field=models.BooleanField(blank=True, help_text='Indifferent', null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Kuks',
            field=models.BooleanField(blank=True, help_text='Kuks', null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Latitude',
            field=models.FloatField(help_text='Latitude', max_length=20),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Location',
            field=models.TextField(blank=True, help_text='Location', null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Longitude',
            field=models.FloatField(help_text='Longitude', max_length=20),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Moans',
            field=models.BooleanField(blank=True, help_text='Moans', null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='OtherActivities',
            field=models.CharField(blank=True, help_text='Other Activities', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='PrimaryFurColor',
            field=models.CharField(blank=True, help_text='Primary Fur Color', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Quaas',
            field=models.BooleanField(blank=True, help_text='Quaas', null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Running',
            field=models.BooleanField(blank=True, help_text='Running', null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='RunsFrom',
            field=models.BooleanField(blank=True, help_text='Runs From', null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='Shift',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', help_text='Shift', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='SpecificLocation',
            field=models.CharField(blank=True, help_text='Specific Location', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='TailFlags',
            field=models.BooleanField(blank=True, help_text='Tail Flags', null=True),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='TailTwitches',
            field=models.BooleanField(blank=True, help_text='Tail Twiches', null=True),
        ),
    ]
