# Generated by Django 3.1.2 on 2020-10-22 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SquirrelApp', '0013_auto_20201022_0153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='Date',
            field=models.DateField(blank=True, help_text='Date', null=True),
        ),
    ]
