# Generated by Django 3.1.2 on 2020-10-22 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SquirrelApp', '0015_auto_20201022_1447'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Squirrel',
        ),
    ]
